### PR TITLE
Enhancement: Throw \InvalidArgumentException if file does not exist

### LINKED ISSUE #41: `Browser::attachFile()` should check if file exists
Currently, if the file doesn't exist, it silently doesn't add.

### PR DESCRIPTION
**Pull request by OskarStark**
closes #41

For better DX

@kbond not sure how to adjust the tests and if this is the right direction

### CODE REVIEW

**Comment by OskarStark** [comment]
cc @silasjoisten

File: src/Browser/Mink/BrowserKitDriver.php [hunk 1]
```diff
@@ -419,12 +419,17 @@ public function isChecked($xpath)
 
     public function attachFile($xpath, $path)
     {
+
```
Comment (OskarStark) [inline src/Browser/Mink/BrowserKitDriver.php]:
```suggestion
```

**Comment by kbond** [comment]
Thanks @OskarStark!
